{{- if .Values.postgresql.enabled }}

apiVersion: v1 
kind: ConfigMap
metadata:
  name: postgresql-backups-script
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "scripts/postgresql.sh").AsConfig | indent 2 }}
---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: postgresql-restores-script
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "scripts/postgresql-restore.sh").AsConfig | indent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-snapshotter
  namespace: {{ .Values.postgresql.config.namespace }}
spec:
  storageClassName: {{ .Values.postgresql.config.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.config.diskSize }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "postgresql-backup"
  namespace: {{ .Values.postgresql.config.namespace }}
spec:
  schedule: {{ .Values.postgresql.config.schedule }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          volumes:
          - name: scripts
            configMap:
              name: postgresql-backups-script
              defaultMode: 0700
          - name: postgresql-snapshotter
            persistentVolumeClaim:
              claimName: postgresql-snapshotter
          - name: aws-credential
            secret: 
              secretName: aws-credential
          containers:
            - image: public.ecr.aws/aws-cli/aws-cli
              name: postgresql-snapshotter
              env:
                - name: POSTGRESQL_CONNECTION_STRING
                  value: "{{ .Values.postgresql.config.connectionString }}"
                - name: BUCKET_NAME
                  value: "{{ .Values.postgresql.config.bucketName }}"
                - name: BACKUP_PATH
                  value: "{{ .Values.postgresql.config.path }}"
                - name: MAX_BACKUPS
                  value: "{{ .Values.postgresql.config.maxBackups }}"
                - name: POSTGRESQL_USERNAME
                  value: "root"
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Values.postgresql.config.secret }}"
                      key: postgres-password
                      optional: false
              volumeMounts:
                - mountPath: "/postgresqldump"
                  name: postgresql-snapshotter
                - name: scripts
                  mountPath: /scripts
                - name: aws-credential
                  mountPath: /root/.aws
              command:
                - "/scripts/postgresql.sh"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-backup-0
  namespace: {{ .Values.postgresql.config.namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.postgresql.config.serviceAccount }}
      volumes:
      - name: scripts
        configMap:
          name: postgresql-backups-script
          defaultMode: 0777
      - name: postgresql-snapshotter
        persistentVolumeClaim:
          claimName: postgresql-snapshotter
      - name: aws-credential
        secret: 
          secretName: aws-credential
      containers:
        - image: public.ecr.aws/aws-cli/aws-cli
          name: postgresql-snapshotter
          env:
            - name: POSTGRESQL_CONNECTION_STRING
              value: "{{ .Values.postgresql.config.connectionString }}"
            - name: BUCKET_NAME
              value: "{{ .Values.postgresql.config.bucketName }}"
            - name: BACKUP_PATH
              value: "{{ .Values.postgresql.config.path }}"
            - name: MAX_BACKUPS
              value: "{{ .Values.postgresql.config.maxBackups }}"
            - name: POSTGRESQL_USERNAME
              value: "root"
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresql.config.secret }}"
                  key: postgres-password
                  optional: false
          volumeMounts:
            - mountPath: "/postgresqldump"
              name: postgresql-snapshotter
            - name: scripts
              mountPath: /scripts
            - name: aws-credential
              mountPath: /root/.aws
          command:
            - "/scripts/postgresql.sh"
            # - "tail"
            # - "-f"
            # - "/dev/null"
      restartPolicy: Never
  backoffLimit: 1
---
{{- if .Values.postgresql.restore }}
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-restore
  namespace: {{ .Values.postgresql.config.namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.postgresql.config.serviceAccount }}
      volumes:
      - name: scripts
        configMap:
          name: postgresql-restores-script
          defaultMode: 0777
      - name: postgresql-snapshotter
        persistentVolumeClaim:
          claimName: postgresql-snapshotter
      - name: aws-credential
        secret:
          secretName: aws-credential
      containers:
        - image: postgres:latest
          name: postgresql-restore
          env:
            - name: BUCKET_NAME
              value: "{{ .Values.postgresql.config.bucketName }}"
            - name: BACKUP_PATH
              value: "{{ .Values.postgresql.config.path }}"
            - name: POSTGRESQL_CONNECTION_STRING
              value: "{{ .Values.postgresql.config.connectionString }}"
            - name: POSTGRESQL_USERNAME
              value: "root"
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresql.config.secret }}"
                  key: postgres-password
                  optional: false
          volumeMounts:
            - mountPath: "/postgresqldump"
              name: postgresql-snapshotter
            - mountPath: /scripts
              name: scripts
            - mountPath: /root/.aws
              name: aws-credential
          command:
            - "/scripts/postgresql-restore.sh"
      restartPolicy: Never
  backoffLimit: 1
{{- end }}
{{- end }}