{{- if .Values.mongo.enabled }}

apiVersion: v1 
kind: ConfigMap
metadata:
  name: mongo-backups-script
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "scripts/mongodb.sh").AsConfig | indent 2 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-snapshotter
  namespace: {{ .Values.mongo.config.namespace }}
spec:
  storageClassName: {{ .Values.mongo.config.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.config.diskSize }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "mongo-backup"
  namespace: {{ .Values.mongo.config.namespace }}
spec:
  schedule: {{ .Values.mongo.config.schedule }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          volumes:
          - name: scripts
            configMap:
              name: mongo-backups-script
              defaultMode: 0700
          - name: mongo-snapshotter
            persistentVolumeClaim:
              claimName: mongo-snapshotter
          - name: aws-credential
            secret: 
              secretName: aws-credential
          containers:
            - image: public.ecr.aws/aws-cli/aws-cli
              name: mongo-snapshotter
              env:
                - name: MONGO_CONNECTION_STRING
                  value: "{{ .Values.mongo.config.connectionString }}"
                - name: BUCKET_NAME
                  value: "{{ .Values.mongo.config.bucketName }}"
                - name: BACKUP_PATH
                  value: "{{ .Values.mongo.config.path }}"
                - name: MAX_BACKUPS
                  value: "{{ .Values.mongo.config.maxBackups }}"
                - name: MONGO_USERNAME
                  value: "root"
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "{{ .Values.mongo.config.secret }}"
                      key: mongodb-root-password
                      optional: false
              volumeMounts:
                - mountPath: "/mongodump"
                  name: mongo-snapshotter
                - name: scripts
                  mountPath: /scripts
                - name: aws-credential
                  mountPath: /root/.aws
              command:
                - "/scripts/mongodb.sh"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-backup-0
  namespace: {{ .Values.mongo.config.namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.mongo.config.serviceAccount }}
      volumes:
      - name: scripts
        configMap:
          name: mongo-backups-script
          defaultMode: 0777
      - name: mongo-snapshotter
        persistentVolumeClaim:
          claimName: mongo-snapshotter
      - name: aws-credential
        secret: 
          secretName: aws-credential
      containers:
        - image: public.ecr.aws/aws-cli/aws-cli
          name: mongo-snapshotter
          env:
            - name: MONGO_CONNECTION_STRING
              value: "{{ .Values.mongo.config.connectionString }}"
            - name: BUCKET_NAME
              value: "{{ .Values.mongo.config.bucketName }}"
            - name: BACKUP_PATH
              value: "{{ .Values.mongo.config.path }}"
            - name: MAX_BACKUPS
              value: "{{ .Values.mongo.config.maxBackups }}"
            - name: MONGO_USERNAME
              value: "root"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.mongo.config.secret }}"
                  key: mongodb-root-password
                  optional: false
          volumeMounts:
            - mountPath: "/mongodump"
              name: mongo-snapshotter
            - name: scripts
              mountPath: /scripts
            - name: aws-credential
              mountPath: /root/.aws
          command:
            - "/scripts/mongodb.sh"
            # - "tail"
            # - "-f"
            # - "/dev/null"
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-restore
  namespace: {{ .Values.mongo.config.namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.mongo.config.serviceAccount }}
      volumes:
      - name: scripts
        configMap:
          name: mongo-restores-script
          defaultMode: 0777
      - name: mongo-snapshotter
        persistentVolumeClaim:
          claimName: mongo-snapshotter
      - name: aws-credential
        secret:
          secretName: aws-credential
      containers:
        - image: mongo:latest
          name: mongo-restore
          env:
            - name: BUCKET_NAME
              value: "{{ .Values.mongo.config.bucketName }}"
            - name: BACKUP_PATH
              value: "{{ .Values.mongo.config.path }}"
            - name: MONGO_CONNECTION_STRING
              value: "{{ .Values.mongo.config.connectionString }}"
            - name: MONGO_USERNAME
              value: "root"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.mongo.config.secret }}"
                  key: mongodb-root-password
                  optional: false
          volumeMounts:
            - mountPath: "/mongodump"
              name: mongo-snapshotter
            - mountPath: /scripts
              name: scripts
            - mountPath: /root/.aws
              name: aws-credential
          command:
            - "/scripts/mongodb-restore.sh"
      restartPolicy: Never
  backoffLimit: 1

{{- end }}