apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-deployments
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      - pods 
      - pods/exec
      - configmaps
    verbs:
      - get
      - list
      - create
      - watch
      - exec 
  - apiGroups:
      - extensions
    resources:
      - deployments
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - exec
  - apiGroups:
      - apps
    resources:
      - deployments
      - configmaps
    verbs:
      - get
      - list
      - create
      - exec
      - watch