config:
  flaskes:
    enabled: false
    replicas: 1
    name: flaskes
    image: aaronortijimn/flaskes
  flaskmg:
    enabled: true
    replicas: 1
    name: flaskmg
    image: aaronortijimn/flaskmg
