neo4j:
  name: ic4302
  resources:
    cpu: "0.5"
    memory: "2Gi"
  config:
     dbms.security.auth_enabled: "false"
  # Uncomment to set the initial password
  #password: "neo4j"

  # Uncomment to use enterprise edition
  edition: "enterprise"
  acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi