mongo:
  enabled: false
  restore: false
  backup: false
  config:
    namespace: default
    connectionString: databases-mongodb.default.svc.cluster.local:27017
    bucketName: tec-ic4302-02-2023
    path: 2022437529/mongodb
    maxBackups: 3
    secret: databases-mongodb
    name: mongo 
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: aws
    type: backup
neo4j:
  enabled: false
  restore: false
  backup: false
  config:
    namespace: default
    connectionString: databases-admin.default.svc.cluster.local:6362
    bucketName: tec-ic4302-02-2023
    path: 2022437529/neo4j
    maxBackups: 3
    secret: ic4302-auth
    name: neo4j 
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: aws
    type: backup
couchdb:
  enabled: false
  restore: true
  backup: false
  config:
    namespace: default
    connectionString: databases-admin.default.svc.cluster.local:5984
    bucketName: tec-ic4302-02-2023
    path: 2022437529/couchdb
    maxBackups: 3
    secret: databases-couchdb
    name: couchdb 
    schedule: "0 */12 * * *"
    diskSize: 2Gi
    storageClass: hostpath
    provider: aws
    type: backup
mariadb:
  enabled: false
  config:
    namespace: default
    connectionString: databases-admin.default.svc.cluster.local:3306
    bucketName: tec-ic4302-02-2023
    path: 2022437529/mariadb
    maxBackups: 3
    secret: databases-mariadb
    name: mariadb
    schedule: "0 */12 * * *"
    diskSize: 2Gi
    storageClass: hostpath
    provider: aws
    type: backup

postgresql:
  enabled: true
  restore: true
  config:
    namespace: default
    connectionString: databases-admin.default.svc.cluster.local:5432
    bucketName: tec-ic4302-02-2023
    path: 2022437529/postgresql
    maxBackups: 3
    secret: databases-postgresql
    name: postgresql
    schedule: "0 */12 * * *"
    diskSize: 2Gi
    storageClass: hostpath
    provider: aws
    type: backup