mongo:
  enabled: false
  config:
    namespace: default
    connectionString: databases-mongodb.default.svc.cluster.local:27017
    bucketName: tec-ic4302-02-2023
    path: 2022437529/mongodb
    maxBackups: 3
    secret: databases-mongodb
    name: mongo 
    schedule: "0 */12 * * *"
    diskSize: 2
    storageClass: hostpath
    provider: aws
    type: backup
neo4j:
  enabled: false
  config:
    namespace: default
    connectionString: databases-admin.default.svc.cluster.local:6362
    bucketName: tec-ic4302-02-2023
    path: 2022437529/neo4j
    maxBackups: 3
    secret: ic4302-auth
    name: neo4j 
    schedule: "0 */12 * * *"
    diskSize: 2Gi
    storageClass: hostpath
    provider: aws
    type: backup
couchdb:
  enabled: true
  config:
    namespace: default
    connectionString: databases-admin.default.svc.cluster.local:5984
    bucketName: tec-ic4302-02-2023
    path: 2022437529/couchdb
    maxBackups: 3
    secret: ic4302-auth
    name: couchdb 
    schedule: "0 */12 * * *"
    diskSize: 2Gi
    storageClass: hostpath
    provider: aws
    type: backup