{{- if .Values.elasticsearch.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticsearch.name }}
spec:
  version: {{ .Values.elasticsearch.version }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true 
  nodeSets:
  - name: master
    count: {{ .Values.elasticsearch.master.replicas }}
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 2Gi
    config:
      node.roles: ["master"]
      node.store.allow_mmap: false
  - name: data
    count: {{ .Values.elasticsearch.data.replicas }}
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 250Mi
              cpu: 1
            limits:
              memory: 500Mi
    config:
      node.roles: ["data"]
      node.store.allow_mmap: false
---
apiVersion: v1
kind: Service
metadata:
  name: pdp-data-nodeport
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
  selector:
    app.kubernetes.io/instance: opensearch
    app.kubernetes.io/name: opensearch
  type: NodePort
{{- end }}
            
   